import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => (
    <div>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>
            main
        </main>
        <footer>
            footer
        </footer>
    </div>
);

export default Home;
